// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHNsh_v1reyPNWXvsCKMbsyxaTI-77Na4',
    appId: '1:973600775508:android:b312359aba28abe0ac7cc1',
    messagingSenderId: '973600775508',
    projectId: 'aforoapp-3b053',
    databaseURL: 'https://aforoapp-3b053-default-rtdb.firebaseio.com',
    storageBucket: 'aforoapp-3b053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvbnwhnJhn9V8xYsP9MvTJiRdcUdwnyqk',
    appId: '1:973600775508:ios:bd94e4ffd4797e1cac7cc1',
    messagingSenderId: '973600775508',
    projectId: 'aforoapp-3b053',
    databaseURL: 'https://aforoapp-3b053-default-rtdb.firebaseio.com',
    storageBucket: 'aforoapp-3b053.appspot.com',
    iosClientId: '973600775508-pjtdeskao46crjpkmar1rimvr43v1fjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aforoApp',
  );
}
